services:
  db:
    image: postgres:15-alpine
    container_name: sor_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sor_network

  backend:
    build: ./backend
    container_name: sor_backend
    restart: always
    environment:
      - APP_ENV=${APP_ENV}
      - IS_SERVER=${IS_SERVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_IP=${SERVER_IP}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sor_network

  ai:
    build: ./ai_service
    container_name: sor_ai
    restart: always
    ports:
      - "8001:8000"
    networks:
      - sor_network

networks:
  sor_network:
    driver: bridge
