services:
  db:
    image: postgres:15-alpine
    container_name: sor_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=twoje_bezpieczne_haslo
      - POSTGRES_DB=sor_system
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sor_network

  backend:
    build: ./backend
    container_name: sor_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:twoje_bezpieczne_haslo@db:5432/sor_system
      - AI_SERVICE_URL=http://ai:8000/predict
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sor_network

  ai:
    build: ./ai_service
    container_name: sor_ai
    restart: always
    ports:
      - "8001:8000"
    networks:
      - sor_network

networks:
  sor_network:
    driver: bridge
